PUT http://localhost:8080/CreateExpensesDetail HTTP/1.1
Content-Type: application/json
//Authorization: token {{client_id}}
Accept: application/json

{
    "ExpensesId": 3,
    "ExpensesType": "CREDIT",
    "ExpensesDesc": "ค่าบัตร KTC",
    "ExpensesAmount": 3442.75
}