basePath: /api/v1
definitions:
  dtos.DefaultResponse:
    properties:
      data: {}
      date:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
  dtos.ExpensesDetail:
    properties:
      expensesAmount:
        type: number
      expensesDesc:
        type: string
      expensesId:
        type: integer
      expensesType:
        type: string
    type: object
  dtos.GetExpensesDetailById:
    properties:
      id:
        type: integer
    type: object
  github_com_9cps_api-go-gin_dtos_request.Expenses:
    properties:
      expensesMoney:
        type: number
      expensesMonth:
        type: integer
      expensesYear:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example Golang APIs
  version: "1.0"
paths:
  /Expenses/CreateExpenses:
    post:
      consumes:
      - application/json
      parameters:
      - description: Expense data
        in: body
        name: req_dtos.Expenses
        required: true
        schema:
          $ref: '#/definitions/github_com_9cps_api-go-gin_dtos_request.Expenses'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Create expenses
      tags:
      - Expenses
  /Expenses/CreateExpensesDetail:
    post:
      consumes:
      - application/json
      parameters:
      - description: ExpensesDetail data
        in: body
        name: req_dtos.ExpensesDetail
        required: true
        schema:
          $ref: '#/definitions/dtos.ExpensesDetail'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Create expenses
      tags:
      - Expenses
  /Expenses/GetListMoneyCard:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Get list money item
      tags:
      - Expenses
  /Expenses/GetListMoneyCardDetail:
    post:
      consumes:
      - application/json
      parameters:
      - description: GetListMoneyCardDetail data
        in: body
        name: req_dtos.GetExpensesDetailById
        required: true
        schema:
          $ref: '#/definitions/dtos.GetExpensesDetailById'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Get list money detail item
      tags:
      - Expenses
  /HealthCheck/Api:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Show status api
      tags:
      - HealthCheck
  /HealthCheck/Database:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Show status database
      tags:
      - HealthCheck
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
