basePath: /api/v1
definitions:
  dtos.DefaultResponse:
    properties:
      data: {}
      date:
        type: string
      message:
        type: string
      status:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a sample server celler server.
  title: Swagger Example Golang APIs
  version: "1.0"
paths:
  /healthcheck/HealthCheckAPI:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Show status api
      tags:
      - healthcheck
  /healthcheck/HealthCheckDB:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.DefaultResponse'
      summary: Show status database
      tags:
      - healthcheck
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
